version: '3.4'

services:
  db:
    image: gsajorato/rest-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: MySql/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: developer
      MYSQL_USER: developer
      MYSQL_PASSWORD: developer
      MYSQL_DATABASE: rest_aspnet_core
    ports:
      - "172.21.0.1:3306:3306"
    networks:
      - rest-core-network

  restnetcore.api:
    image: gsajorato/restnetcore
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production,
      CONNECTION_STRING: Server=172.21.0.1;Port=3306;Uid=developer;Pwd=developer;
      DATABASE_NAME: rest_aspnet_core
    ports:
      - "0.0.0.0:8089:9090"
    links:
      - db
    depends_on:
      - db
    networks: 
      - rest-core-network

networks: 
    rest-core-network:
        driver: bridge
