FROM microsoft/dotnet:2.1-sdk AS builder
WORKDIR /source
COPY ./src .
RUN dotnet restore
RUN dotnet publish ./Sample.BasicRestAspnetCore.Host --output /app/

FROM microsoft/dotnet:2.1-aspnetcore-runtime-alpine3.7
WORKDIR /app
COPY --from=builder /app .

ENTRYPOINT ["dotnet", "Sample.BasicRestAspnetCore.Host.dll"]